spring:
  application:
    name: medicines-service

  config:
    import: configserver:http://localhost:8888

  cache:
    redis:
      time-to-live: 10m
    type: redis

  data:
    redis:
      host: localhost
      port: 6379